### ISSUE TITLE
iuwandbox(proposal) : 複数の翻訳単位の対応

### ISSUE THREAD

**Issue by yumetodo** [srz-zumix/iutest#11]
http://melpon.org/wandbox/permlink/WlbTScmW4ofzbE2E

のように複数の翻訳単位を作れるようなので将来的に対応してもいいかもしれない。具体的にはinclude解析部分に手を加える必要がある。

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/kazatsuyu">@kazatsuyu</a> ほう、ますますstatic/extern/inlineまわりわかんねぇ・・・。<br><br>ところでwandboxで複数の翻訳単位作る方法あったのか・・・<a href="https://twitter.com/srz_zumix">@srz_zumix</a> 氏のiuwandboxつかっててヘッダーオンリーなものしか使えないイメージだった</p>&mdash; yumetodo-C++erだけど化学科 (@yumetodo) <a href="https://twitter.com/yumetodo/status/787531223589543936">2016年10月16日</a></blockquote>

**Comment by srz-zumix** [comment]
対応してみました。
ただ、あまりにもたくさんのコードをビルドしようとすると、リソース制限かタイムアウトで wandbox から kill されるみたいです。

**Comment by yumetodo** [comment]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/yumetodo">@yumetodo</a> wandboxのインスタンスはおそらく4コア使えるので、Makefile書いて-j4で実行するようにするとものによってはタイムアウトしなくなる可能性がある</p>&mdash; 白山風露 (@kazatsuyu) <a href="https://twitter.com/kazatsuyu/status/806405975565541377">2016年12月7日</a></blockquote>
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/yumetodo">@yumetodo</a> Languages &gt; Bash script<br>wandboxの環境の中でなら何でもできる</p>&mdash; 白山風露 (@kazatsuyu) <a href="https://twitter.com/kazatsuyu/status/806407775597297664">2016年12月7日</a></blockquote>


wandboxのポテンシャルを舐めていた。make -j4すればもっと高速になる可能性があるのか・・・。

**Comment by srz-zumix** [comment]
2d35a70 で少し対応してみたのですが、今の wandbox だと make 使えないっぽい感じでした。
--make オプションを付与すると Makefile と bash script を生成します。（コンパイラの選択は未対応）
https://wandbox.org/permlink/MxvZKPP4Qt0nlHgL

**Comment by srz-zumix** [comment]
wandbox 側で make 使えるようになったら reopen します
