### ISSUE TITLE
iuwandbox: -fオプションのパーサーはスペースを\nに置換するべきではないか

### ISSUE THREAD

**Issue by yumetodo** [srz-zumix/iutest#13]
``-f``オプションで
``-f"-O2 -DNO_RDSEED"``
のように渡すと

```
compiler_message:
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
cc1plus: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
```

のように怒られる。

ex.) http://melpon.org/wandbox/permlink/LA263I1vQuyfMqlE

つまりspaceを``\n``に置換する必要がある。

ただ、(ほとんど指定することないけど)``-x c++``みたいなオプションもあるので置換が面倒そう。

**Comment by srz-zumix** [comment]
-f オプションは複数つけることができるので、
-f"-O2" -f"-DNO_RDSEED"
とすることで回避できると思います。

**Comment by srz-zumix** [comment]
置換については検証・検討してみます

**Comment by yumetodo** [comment]
とりあえず自力で``\n``置換して対応しています。

**Comment by srz-zumix** [comment]
置換するように修正しました。
-x c++ も正しく処理されると思います。

**Comment by yumetodo** [comment]
そもそも一体いつ``-x c++``なんてオプションが必要なのか言い出した私がわかっていない・・・

とりあえず``-O2 -DNO_RDSEED -DNO_RDRAND``は大丈夫でした。
http://melpon.org/wandbox/permlink/5JIm3CijXJCYr2l0
なぜにか別のエラーが出てますけどね・・・うーむ。

**Comment by srz-zumix** [comment]
boost test が定義している main と重複しちゃってますね。
boost 外すと OK そうな感じがします。

**Comment by yumetodo** [comment]
うーん、今回はboost使わないからいいけど、これboost有効の場合、wandboxの仕様的にありったけ全部のBoostのlibとリンクしようとするのか・・・
https://github.com/melpon/wandbox/issues/179
https://github.com/melpon/wandbox/blob/dcbb638b3859b7c887965cc6a74781a86e20630f/cattleshed/configure.ac

**Comment by srz-zumix** [comment]
調査した結果、最初のソースファイル（prog.cc）に main がないとリンカエラーになるようです。
iuwandbox では main の正確な検出は難しそうだなと思ったので、
hint を print するようにだけしました。
