### ISSUE TITLE
参照されていない関数 (iuDebugInitialize, iuDebugBreakAlloc) の警告 C4505

### ISSUE THREAD

**Issue by mogemimi** [srz-zumix/iutest#3]
こんにちは、
毎日楽しく iutest を使って CI を回しております。

iutest をインクルードしたテストアプリケーションを Visual Studio でビルドするときに、iutest のヘッダーファイル内で次の警告が表示されます。

```cmd
>c:\iutest\include\impl\../internal/iutest_debug.hpp(44): warning C4505: 'iutest::detail::iuDebugInitialize': unreferenced local function has been removed
>c:\iutest\include\impl\../internal/iutest_debug.hpp(53): warning C4505: 'iutest::detail::iuDebugBreakAlloc': unreferenced local function has been removed
```

コンパイラオプションで「警告をエラーとして扱う」ように設定しているので、テストアプリケーションのビルドが上手く通らず少々困っております。

```cmd
>c:\iutest\include\impl\../internal/iutest_debug.hpp(44): error C2220: warning treated as error - no 'object' file generated
```

具体的なビルド環境は次の通りです:

- ヘッダーオンリーで iutest (バージョンは r834) を使用しています
- `_IUTEST_DEBUG` プリプロセッサは定義していません
- `<gtest/iutest_switch.hpp>` と `<iutest.hpp>` の 2 つをアプリケーション側でインクルードして使っています
- Visual Studio 2015 RC
- Warning Level: Level4 (/W4)
- Treat Warnings As Errors: Yes (/WX)

今は該当する警告を無視するオプション　(`/wd"4505"`)　を追加してコンパイルしています。
警告を無視することなく、ビルドすることはできないでしょうか？よろしくお願いします。:relieved:

**Comment by srz-zumix** [comment]
ご指摘ありがとうございます！
r836 で修正しましたので、ご確認よろしくお願いします。

**Comment by mogemimi** [comment]
無事ビルドが通ることを確認しました。
素早い対応ありがとうございます。とても助かりました！

おかげさまで AppVeyor を使って Visual Studio 向けのテストもできるようになりました :blush:
