### ISSUE TITLE
osdnのほうのドキュメントページについて

### ISSUE THREAD

**Issue by yumetodo** [srz-zumix/iutest#423]
iutestのドキュメントのWebページは大きく分けて

- http://iutest.osdn.jp/doc/
- https://srz-zumix.github.io/iutest/

の2つがあり、Github Pagesのほうのみが更新されていると把握しています(レポジトリそのものは双方更新が続いていることは把握しています)。

下に2020/04/28 23:54にGoogleで`iutest`で検索したときの結果を示します。
![image](https://user-images.githubusercontent.com/10869046/80502630-d984e680-89ab-11ea-9b8c-034454bc7f50.png)

まず最初にosdnのレポのページが出てきて、次にosdnにあるドキュメントページの入門が出てきて、3番目にGithub Pagesが出てきます(~~4番目私のQiitaの記事だ・・・~~)。

下に2020/04/28 23:58にBingで`iutest`で検索したときの結果を示します。
![image](https://user-images.githubusercontent.com/10869046/80503142-7051a300-89ac-11ea-8801-5ebe684d6429.png)

1,2番目は変わらず、3番目はGithub Pagesのiuwandboxのページです。

このように、Github Pagesで公開されているドキュメントよりも、更新されていないosdnのページが上位に来る状態にあります。

また、このプロジェクトの`README.md`には

```md
Documentation
--------------------------------------------------

* in repository  
  doc/index.html  
* online document  
  [least released version(OSDN)](http://iutest.osdn.jp/doc/index.html)  
  [GitHub master branch (gh-pages)](http://srz-zumix.github.io/iutest/)  
```

のように記載されているのですが、`least released version(OSDN)`という文言に反して2017年で更新が止まっています。

したがって3つの選択肢を提案します。

1. least released versionのドキュメント公開をやめてosdnで公開しているドキュメントページからはJavaScriptなどでリダイレクトを掛ける(Googleの検索評価を引き継げます)
2. osdnで公開しているドキュメントページの更新を再開する
3. github pagesでleast released versionとmaster追従しているドキュメントをどちらも公開する(https://docs.opencv.org/ のようにdirectoryを分けるなどして実現)

**Comment by yumetodo** [comment]
ところでosdnのほうを存続する場合、https化はできないものなんでしょうかね

**Comment by srz-zumix** [comment]
OSDN の更新が手動で面倒なので、1. と 3. をやろうと思います。
OSDN の https 化は単純にリンクを変えれば良さそうでした。

**Comment by yumetodo** [comment]
http://iutest.osdn.jp/doc/
からのリダイレクトはまだですかね？

**Comment by srz-zumix** [comment]
以下の予定です

1. #424 が master までマージされる（master のドキュメントが自動生成される）
1. latest バージョンのドキュメントを手動生成して push
1. トップディレクトリのドキュメントを削除
1. トップは opencv のようなルートページを置く
1. OSDN で↑にリダイレクト
1. README.md を更新する

**Comment by yumetodo** [comment]
その場合、トップディレクトリのそれぞれからのリダイレクトもかけないとまずいかもしれない

**Comment by srz-zumix** [comment]
リリースバージョン全部のディレクトリを用意するのはやめて、master/latest の2構成にしました。
OSDN のリダイレクトも設定済みです。

**Comment by yumetodo** [comment]
確認しました。これにてこの件は解決ですかね？
