### ISSUE TITLE
warning C4267(UTF8ToSJIS): size_tからintへの変換

### ISSUE THREAD

**Issue by yumetodo** [srz-zumix/iutest#53]
`iutest_charcode.ipp`の`iutest::detail::UTF8ToSJIS`関数にて。

`MultiByteToWideChar`の第4引数に`size_t`型の値を渡しているが、要求されているのは`int`型なので

```
warning C4267: '引数': 'size_t' から 'int' に変換しました。データが失われているかもしれません。
```

という警告が出る。

**Comment by srz-zumix** [comment]
たしかに int 型に size_t を渡しているのですが、手元の環境で C4267 が出ないですね…
なんでだろ

**Comment by srz-zumix** [comment]
/W4 はつけてるはずですね。VS2017 です。
とりあえず直すとして、AppVeyor で再現取れないかテスト書きます。

**Comment by srz-zumix** [comment]
https://ci.appveyor.com/project/srz-zumix/iutest/build/job/b71yjuovehxfim3p/messages
今見たら警告結構出てたな…
エラーにしたほうがいいかもな…

**Comment by srz-zumix** [comment]
再現できなかったのですが修正しました。
ご確認いただけると幸いです。

**Comment by yumetodo** [comment]
確認できました。
https://bitbucket.org/yumetodo/byteswap_ushort_test

**Comment by srz-zumix** [comment]
🙏
