### ISSUE TITLE
iuwandbox.py : --expand_includeしない場合について

### ISSUE THREAD

**Issue by yumetodo** [srz-zumix/iutest#7]
現在``--expand_include``する場合は``make_code``関数が再帰処理するので確実にヘッダーファイルをコンパイルできるが、しない場合はそれができない。

たとえば

```cpp
#include "../include/string_split.hpp"
```

とあったとして、現状ではこのヘッダーはwandboxに送られるものの、パスが違うのでincludeに失敗します。

現状の``--expand_include``しない場合のルーチンは

1. ``make_code``関数が呼ばれる
2. ``#include``を見つける
3. 存在すればファイルパスを記録
4. ``setup_includes``関数でファイルを開く

となっていますが、これではincludeしているヘッダーからincludeしているファイルを追加できないのでまずいです。

includeしているヘッダーからincludeしていない場合は

```cpp
#ifdef __WANDBOX__
#include "string_split.hpp"
#else
#include "../include/string_split.hpp"
#endif
```

のように対処できたりしますが。

``--expand_include``すればいいだろ、という話は有りますが。

**Comment by srz-zumix** [comment]
ご指摘ありがとうございます。 include したファイルのパス訂正はしていたのですが、 include したファイルから include するファイルのパス訂正はしてませんでした。
修正します。

**Comment by srz-zumix** [comment]
修正しました

**Comment by yumetodo** [comment]
同名のファイルに対応できていないと思います。

ex.)
http://melpon.org/wandbox/permlink/HTkHrTTbeD8ZAT0l

つまり絶対パスを加工した名前(``\``や``/``を``_``に置き換えたり、``..``を``pre``に置き換えたり)にリネームする必要があると思います。(相対パスだと衝突の可能性が消せないかもしれない)

**Comment by srz-zumix** [comment]
おお！その通りですね。
パス加工をもう少し直します！
ちなみに、-I オプション(インクルードパスオプション)って欲しいですか？

**Comment by yumetodo** [comment]
>ちなみに、-I オプション(インクルードパスオプション)って欲しいですか？

需要はありそうですが、実装が複雑になりそう。つまり``#include <...>``にも対応するんですね？

ところでその場合sproutを使った時はどうするんでしょう・・・、``--use-own-sprout``とか追加するんでしょうか？(そもそも現状sproutを使う指定って使えましたっけ)。

**Comment by srz-zumix** [comment]
同名ファイル名に対応しました。

-I は余裕ができたら対応しようと思います。
sprout を使うには --options sprout で有効にできます。
--options に指定できるオプションは --list_options で取得できます。
ただ、よく使いそうなオプションだと思ったので iuwandbox 自体に --sprout オプションを追加しました。

**Comment by yumetodo** [comment]
確認できました。ありがとうございます。
